Data & Python Notebook that corresponds to my lego analysis YouTube tutorial: [https://youtu.be/BzQDi4D0B_M]

In [4]:
# Making a map using the folium module
import folium
phone_map = folium.Map()

# Top three smart phone companies by market share in 2016
companies = [
    {'loc': [13.7527,  79.7067], 'label': 'Datamind: ...%'},]

# Adding markers to the map
for company in companies:
    marker = folium.Marker(location=company['loc'], popup=company['label'])
    marker.add_to(phone_map)

# The last object in the cell always gets shown in the notebook
phone_map

In [5]:
import numpy as np
import pandas as pd

In [6]:
df1=pd.read_csv("lego_sets.csv")

In [7]:
df1

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space
...,...,...,...,...,...,...
11981,NaN,NaN,2014,NaN,NaN,Minecraft
11982,NaN,NaN,2006,NaN,NaN,Super Heroes
11983,NaN,NaN,2017,NaN,NaN,Minecraft
11984,NaN,NaN,2017,8.0,NaN,Super Heroes
11985,NaN,NaN,2003,NaN,NaN,Harry Potter

In [8]:
df1.isnull().sum()

set_num          153
name             153
year               0
num_parts       5060
theme_name       153
parent_theme       0
dtype: int64

In [10]:
df1.dropna(subset=["set_num","name","theme_name"])

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space
...,...,...,...,...,...,...
11828,Wauwatosa-1,"LEGO Store Grand Opening Exclusive Set, Mayfai...",2012,15.0,LEGO Brand Store,LEGO Brand Store
11829,WHITEHOUSE-1,Micro White House,2015,NaN,Promotional,Promotional
11830,Wiesbaden-1,"LEGO Store Grand Opening Exclusive Set, Wiesba...",2010,146.0,LEGO Brand Store,LEGO Brand Store
11831,WishingWell-1,Wishing Well [Toys R Us Promo],2013,NaN,Friends,Friends
11832,wwgp1-1,Wild West Limited Edition Gift Pack,1996,NaN,Cowboys,Western

In [23]:
df1["parent_theme"].unique()

array(['Legoland', 'Town', 'Castle', 'Space', 'Classic', 'Gear',
       'Universal Building Set', 'Train', 'Bulk Bricks', 'Star Wars',
       'Hobby Sets', 'Bionicle', 'Sculptures', 'Discovery', 'Pirates',
       'Seasonal', 'Super Heroes', 'Clikits', 'Sports', 'Harry Potter',
       'Model Team', 'Other', 'Modular Buildings', 'Factory',
       'Service Packs', 'Monster Fighters',
       'The Hobbit and Lord of the Rings', 'Creator', 'Adventurers',
       'Mindstorms', 'Technic', 'Educational and Dacta', 'Duplo',
       'Disney Princess', 'Juniors', 'Friends', 'Aquazone', 'Ninja',
       'Minitalia', 'Books', 'Ninjago', 'Hero Factory', 'Racers',
       'Fabuland', 'Rock Raiders', 'Studios', 'Alpha Team', '4 Juniors',
       'Building Set with People', 'Boat', 'Value Packs', 'Freestyle',
       'Time Cruisers', 'Indiana Jones', 'Master Building Academy',
       'FIRST LEGO League', 'Atlantis', 'Prince of Persia',
       'Architecture', 'LEGO Ideas and CUUSOO', 'Minecraft', 'Fusion',
       'Homemaker', 'Elves', 'Belville', 'Nexo Knights', 'Western',
       'Promotional', 'Toy Story', "Pharaoh's Quest", 'Cars',
       'Pirates of the Caribbean', 'Legends of Chima', 'The Lone Ranger',
       'Teenage Mutant Ninja Turtles', 'The LEGO Movie', 'Jurassic World',
       'Scooby-Doo', 'Designer Sets', 'LEGO Brand Store',
       'Island Xtreme Stunts', 'Znap', "Disney's Mickey Mouse",
       'Spybiotics', 'SpongeBob SquarePants', 'Avatar', 'Exo-Force',
       'Legoland Parks', 'Inventor', 'Brickheadz', 'Mixels', 'X-Pod',
       'Power Miners', 'Collectible Minifigures', 'Speed Champions',
       'Agents', 'LEGO Exclusive', 'Universe', 'Dino', 'Dinosaurs',
       'Vikings', 'Disney', 'Dimensions', 'Dino 2010', 'Dino Attack',
       'Angry Birds', 'Ghostbusters', 'Power Functions', 'Ben 10'],
      dtype=object)

In [ ]:
df2=pd.read_csv("parent_themes.csv")

In [12]:
df2

      id          name  is_licensed
0      1       Technic        False
1     22       Creator        False
2     50          Town        False
3    112        Racers        False
4    126         Space        False
..   ...           ...          ...
106  605  Nexo Knights        False
107  606   Angry Birds         True
108  607  Ghostbusters         True
109  608        Disney         True
110  610    Brickheadz        False

[111 rows x 3 columns]

In [25]:
def func(x):
    return df2[df2["name"]==x]["is_licensed"][0]

In [26]:
func("Technic")

False

In [21]:
df2[df2["name"]=="Technic"]["is_licensed"][0]

False

In [27]:
df1["is_licensed"]=df1["parent_theme"].map(func)

KeyError: 0