In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Q. 1) Show the number of Confirmed, Deaths and Recovered cases in each Region.

In [3]:
df=pd.read_csv("4. covid_19_data.csv")
df

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]

In [6]:
df["Region"].value_counts()

US                58
Mainland China    31
Canada            15
France            11
UK                11
                  ..
Guinea             1
Guinea-Bissau      1
Guyana             1
Haiti              1
Macau              1
Name: Region, Length: 187, dtype: int64

In [8]:
df.dtypes

Date         object
State        object
Region       object
Confirmed     int64
Deaths        int64
Recovered     int64
dtype: object

In [13]:
df.groupby(["Region"])[["Confirmed","Deaths","Recovered"]].sum()

                    Confirmed  Deaths  Recovered
Region
Afghanistan              1939      60        252
Albania                   766      30        455
Algeria                  3848     444       1702
Andorra                   743      42        423
Angola                     27       2          7
...                       ...     ...        ...
West Bank and Gaza        344       2         71
Western Sahara              6       0          5
Yemen                       6       0          1
Zambia                     97       3         54
Zimbabwe                   32       4          5

[187 rows x 3 columns]

In [18]:
df[df["Region"]=="US"]

,Date,State,Region,Confirmed,Deaths,Recovered
181,4/29/2020,Alabama,US,6912,256,0
182,4/29/2020,Alaska,US,355,9,0
186,4/29/2020,Arizona,US,7209,308,0
187,4/29/2020,Arkansas,US,3193,57,0
195,4/29/2020,California,US,48747,1946,0
199,4/29/2020,Colorado,US,14758,766,0
200,4/29/2020,Connecticut,US,26767,2169,0
202,4/29/2020,Delaware,US,4655,144,0
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
205,4/29/2020,District of Columbia,US,4106,205,0
208,4/29/2020,Florida,US,33193,1218,0
213,4/29/2020,Georgia,US,25775,1101,0
216,4/29/2020,Grand Princess,US,103,3,0
219,4/29/2020,Guam,US,141,5,0
224,4/29/2020,Hawaii,US,613,16,0
231,4/29/2020,Idaho,US,1952,60,0
232,4/29/2020,Illinois,US,50358,2215,0
233,4/29/2020,Indiana,US,17182,964,0
235,4/29/2020,Iowa,US,6843,148,0
240,4/29/2020,Kansas,US,3839,134,0
241,4/29/2020,Kentucky,US,4537,234,0
243,4/29/2020,Louisiana,US,27660,1845,0
245,4/29/2020,Maine,US,1056,52,0
248,4/29/2020,Maryland,US,20849,1078,0
249,4/29/2020,Massachusetts,US,60265,3405,0
251,4/29/2020,Michigan,US,40399,3670,0
252,4/29/2020,Minnesota,US,4644,319,0
253,4/29/2020,Mississippi,US,6569,250,0
254,4/29/2020,Missouri,US,7660,338,0
255,4/29/2020,Montana,US,451,16,0
257,4/29/2020,Nebraska,US,3851,56,0
258,4/29/2020,Nevada,US,4934,230,0
261,4/29/2020,New Hampshire,US,2058,60,0
262,4/29/2020,New Jersey,US,116365,6771,0
263,4/29/2020,New Mexico,US,3213,112,0
265,4/29/2020,New York,US,299691,23477,0
268,4/29/2020,North Carolina,US,10180,382,0
269,4/29/2020,North Dakota,US,1033,19,0
270,4/29/2020,Northern Mariana Islands,US,14,2,0
274,4/29/2020,Ohio,US,17303,937,0
275,4/29/2020,Oklahoma,US,3473,214,0
277,4/29/2020,Oregon,US,2446,101,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
280,4/29/2020,Puerto Rico,US,1433,86,0
285,4/29/2020,Recovered,US,0,0,120720
287,4/29/2020,Rhode Island,US,8247,251,0
298,4/29/2020,South Carolina,US,5882,231,0
299,4/29/2020,South Dakota,US,2373,13,0
302,4/29/2020,Tennessee,US,10366,195,0
303,4/29/2020,Texas,US,27257,754,0
307,4/29/2020,Utah,US,4497,45,0
308,4/29/2020,Vermont,US,862,47,0
310,4/29/2020,Virgin Islands,US,57,4,0
311,4/29/2020,Virginia,US,14962,522,0
312,4/29/2020,Washington,US,14070,801,0
313,4/29/2020,West Virginia,US,1110,38,0
315,4/29/2020,Wisconsin,US,6520,308,0
316,4/29/2020,Wyoming,US,545,7,0

In [16]:
df.groupby(["Region"])[["Confirmed","Deaths","Recovered"]].sum().loc["US"]

Confirmed    1039909
Deaths         60967
Recovered     120720
Name: US, dtype: int64

Q. 2) Remove all the records where the Confirmed Cases is Less Than 10.

In [22]:
df[df["Confirmed"]<10]

,Date,State,Region,Confirmed,Deaths,Recovered
18,4/29/2020,NaN,Bhutan,7,0,5
98,4/29/2020,NaN,MS Zaandam,9,2,0
105,4/29/2020,NaN,Mauritania,8,1,6
126,4/29/2020,NaN,Papua New Guinea,8,0,0
140,4/29/2020,NaN,Sao Tome and Principe,8,0,4
177,4/29/2020,NaN,Western Sahara,6,0,5
178,4/29/2020,NaN,Yemen,6,0,1
184,4/29/2020,Anguilla,UK,3,0,3
192,4/29/2020,"Bonaire, Sint Eustatius and Saba",Netherlands,5,0,0
194,4/29/2020,British Virgin Islands,UK,6,1,3
203,4/29/2020,Diamond Princess cruise ship,Canada,0,1,0
272,4/29/2020,Northwest Territories,Canada,5,0,0
284,4/29/2020,Recovered,Canada,0,0,20327
285,4/29/2020,Recovered,US,0,0,120720
288,4/29/2020,Saint Barthelemy,France,6,0,6
289,4/29/2020,Saint Pierre and Miquelon,France,1,0,0
305,4/29/2020,Tibet,Mainland China,1,0,1

In [21]:
len(df[df["Confirmed"]<10])

17

In [23]:
df=df[df["Confirmed"]>10]

In [24]:
df

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[301 rows x 6 columns]

Q. 3) In which Region, maximum number of Confirmed cases were recorded ?

In [25]:
df.sort_values(by="Confirmed",ascending=False)

          Date       State      Region  Confirmed  Deaths  Recovered
265  4/29/2020    New York          US     299691   23477          0
153  4/29/2020         NaN       Spain     236899   24275     132929
80   4/29/2020         NaN       Italy     203591   27682      71252
168  4/29/2020         NaN          UK     165221   26097          0
57   4/29/2020         NaN      France     165093   24087      48228
..         ...         ...         ...        ...     ...        ...
256  4/29/2020  Montserrat          UK         11       1          2
217  4/29/2020   Greenland     Denmark         11       0         11
144  4/29/2020         NaN  Seychelles         11       0          6
318  4/29/2020       Yukon      Canada         11       0          0
27   4/29/2020         NaN     Burundi         11       1          4

[301 rows x 6 columns]

In [27]:
df[df["Confirmed"]==df["Confirmed"].max()]

          Date     State Region  Confirmed  Deaths  Recovered
265  4/29/2020  New York     US     299691   23477          0

In [26]:
df["Confirmed"].max()

299691

In [28]:
df.sort_values(by="Deaths")

,Date,State,Region,Confirmed,Deaths,Recovered
210,4/29/2020,French Polynesia,France,58,0,50
114,4/29/2020,NaN,Namibia,16,0,8
29,4/29/2020,NaN,Cambodia,122,0,119
113,4/29/2020,NaN,Mozambique,76,0,12
31,4/29/2020,NaN,Central African Republic,50,0,10
...,...,...,...,...,...,...
265,4/29/2020,New York,US,299691,23477,0
57,4/29/2020,NaN,France,165093,24087,48228
153,4/29/2020,NaN,Spain,236899,24275,132929
168,4/29/2020,NaN,UK,165221,26097,0
80,4/29/2020,NaN,Italy,203591,27682,71252

In [31]:
print(df.sort_values(by="Deaths")[["State","Region","Deaths"]].to_string())

                            State                            Region  Deaths
210              French Polynesia                            France       0
114                           NaN                           Namibia       0
29                            NaN                          Cambodia       0
113                           NaN                        Mozambique       0
31                            NaN          Central African Republic       0
110                           NaN                          Mongolia       0
259                 New Brunswick                            Canada       0
260                 New Caledonia                            France       0
99                            NaN                        Madagascar       0
115                           NaN                             Nepal       0
90                            NaN                              Laos       0
271            Northern Territory                         Australia       0
279          Prince Edward Island                            Canada       0
281                       Qinghai                    Mainland China       0
286                       Reunion                            France       0
45                            NaN                          Dominica       0
64                            NaN                           Grenada       0
55                            NaN                              Fiji       0
294                        Shanxi                    Mainland China       0
267                       Ningxia                    Mainland China       0
237                       Jiangsu                    Mainland China       0
244                         Macau                             Macau       0
175                           NaN                           Vietnam       0
318                         Yukon                            Canada       0
207                 Faroe Islands                           Denmark       0
206   Falkland Islands (Malvinas)                                UK       0
204  Diamond Princess cruise ship                                US       0
214                     Gibraltar                                UK       0
215                Grand Princess                            Canada       0
217                     Greenland                           Denmark       0
135                           NaN                            Rwanda       0
169                           NaN                            Uganda       0
51                            NaN                           Eritrea       0
152                           NaN                       South Sudan       0
136                           NaN             Saint Kitts and Nevis       0
163                           NaN                       Timor-Leste       0
138                           NaN  Saint Vincent and the Grenadines       0
137                           NaN                       Saint Lucia       0
144                           NaN                        Seychelles       0
196                Cayman Islands                                UK       1
95                            NaN                     Liechtenstein       1
201                       Curacao                       Netherlands       1
209                 French Guiana                            France       1
67                            NaN                     Guinea-Bissau       1
256                    Montserrat                                UK       1
53                            NaN                          Eswatini       1
239                         Jilin                    Mainland China       1
211                        Fujian                    Mainland China       1
234                Inner Mongolia                    Mainland China       1
238                       Jiangxi                    Mainland China       1
320                      Zhejiang                    Mainland China       1
102                           NaN                          Maldives       1
27                            NaN                           Burundi       1
17                            NaN                             Benin       1
28                            NaN                        Cabo Verde       1
23                            NaN                            Brunei       1
306      Turks and Caicos Islands                                UK       1
50                            NaN                 Equatorial Guinea       1
21                            NaN                          Botswana       1
94                            NaN                             Libya       2
270      Northern Mariana Islands                                US       2
221                       Guangxi                    Mainland China       2
32                            NaN                              Chad       2
176                           NaN                West Bank and Gaza       2
4                             NaN                            Angola       2
222                       Guizhou                    Mainland China       2
212                         Gansu                    Mainland China       2
319                        Yunnan                    Mainland China       2
16                            NaN                            Belize       2
44                            NaN                          Djibouti       2
242                      Liaoning                    Mainland China       2
188                         Aruba                       Netherlands       2
266     Newfoundland and Labrador                            Canada       3
100                           NaN                            Malawi       3
54                            NaN                          Ethiopia       3
300                     St Martin                            France       3
304                       Tianjin                    Mainland China       3
295                       Sichuan                    Mainland China       3
179                           NaN                            Zambia       3
216                Grand Princess                                US       3
5                             NaN               Antigua and Barbuda       3
291                       Shaanxi                    Mainland China       3
189  Australian Capital Territory                         Australia       3
118                           NaN                         Nicaragua       3
159                           NaN                             Syria       3
317                      Xinjiang                    Mainland China       3
58                            NaN                             Gabon       3
230                         Hunan                    Mainland China       4
228                     Hong Kong                         Hong Kong       4
109                           NaN                            Monaco       4
104                           NaN                             Malta       4
145                           NaN                      Sierra Leone       4
250                       Mayotte                            France       4
310                Virgin Islands                                US       4
297               South Australia                         Australia       4
180                           NaN                          Zimbabwe       4
219                          Guam                                US       5
198                     Chongqing                    Mainland China       6
60                            NaN                           Georgia       6
191                       Bermuda                                UK       6
290                  Saskatchewan                            Canada       6
69                            NaN                             Haiti       6
246                      Manitoba                            Canada       6
283                    Queensland                         Australia       6
185                         Anhui                    Mainland China       6
160                           NaN                            Taiwan       6
26                            NaN                             Burma       6
37                            NaN                        Costa Rica       6
225                         Hebei                    Mainland China       6
223                        Hainan                    Mainland China       6
293                      Shanghai                    Mainland China       7
292                      Shandong                    Mainland China       7
316                       Wyoming                                US       7
66                            NaN                            Guinea       7
82                            NaN                           Jamaica       7
154                           NaN                         Sri Lanka       7
111                           NaN                        Montenegro       7
164                           NaN                              Togo       7
13                            NaN                          Barbados       7
165                           NaN               Trinidad and Tobago       8
220                     Guangdong                    Mainland China       8
84                            NaN                            Jordan       8
11                            NaN                           Bahrain       8
35                            NaN               Congo (Brazzaville)       8
89                            NaN                        Kyrgyzstan       8
314             Western Australia                         Australia       8
68                            NaN                            Guyana       8
190                       Beijing                    Mainland China       9
127                           NaN                          Paraguay       9
173                           NaN                        Uzbekistan       9
182                        Alaska                                US       9
49                            NaN                       El Salvador       9
142                           NaN                           Senegal       9
174                           NaN                         Venezuela      10
132                           NaN                             Qatar      10
73                            NaN                           Iceland      10
123                           NaN                              Oman      10
106                           NaN                         Mauritius      10
10                            NaN                           Bahamas      11
301                      Tasmania                         Australia      12
87                            NaN                            Kosovo      12
218                    Guadeloupe                            France      12
296                  Sint Maarten                       Netherlands      13
43                            NaN                  Diamond Princess      13
299                  South Dakota                                US      13
226                  Heilongjiang                    Mainland China      13
146                           NaN                         Singapore      14
81                            NaN                       Ivory Coast      14
247                    Martinique                            France      14
86                            NaN                             Kenya      15
40                            NaN                            Cyprus      15
91                            NaN                            Latvia      15
172                           NaN                           Uruguay      15
93                            NaN                           Liberia      16
65                            NaN                         Guatemala      16
62                            NaN                             Ghana      16
224                        Hawaii                                US      16
255                       Montana                                US      16
161                           NaN                          Tanzania      16
309                      Victoria                         Australia      18
269                  North Dakota                                US      19
117                           NaN                       New Zealand      19
236                   Isle of Man                                UK      21
147                           NaN                          Slovakia      22
227                         Henan                    Mainland China      22
9                             NaN                        Azerbaijan      23
92                            NaN                           Lebanon      24
88                            NaN                            Kuwait      24
103                           NaN                              Mali      25
85                            NaN                        Kazakhstan      25
273                   Nova Scotia                            Canada      28
149                           NaN                           Somalia      28
155                           NaN                             Sudan      28
1                             NaN                           Albania      30
7                             NaN                           Armenia      30
36                            NaN                  Congo (Kinshasa)      30
119                           NaN                             Niger      32
197               Channel Islands                                UK      38
313                 West Virginia                                US      38
264               New South Wales                         Australia      40
166                           NaN                           Tunisia      40
139                           NaN                        San Marino      41
3                             NaN                           Andorra      42
25                            NaN                      Burkina Faso      43
307                          Utah                                US      45
96                            NaN                         Lithuania      45
308                       Vermont                                US      47
52                            NaN                           Estonia      50
120                           NaN                           Nigeria      51
245                         Maine                                US      52
162                           NaN                          Thailand      54
257                      Nebraska                                US      56
187                      Arkansas                                US      57
39                            NaN                              Cuba      58
19                            NaN                           Bolivia      59
231                         Idaho                                US      60
261                 New Hampshire                                US      60
0                             NaN                       Afghanistan      60
30                            NaN                          Cameroon      61
24                            NaN                          Bulgaria      64
20                            NaN            Bosnia and Herzegovina      65
71                            NaN                          Honduras      66
38                            NaN                           Croatia      67
121                           NaN                   North Macedonia      73
14                            NaN                           Belarus      84
280                   Puerto Rico                                US      86
183                       Alberta                            Canada      87
148                           NaN                          Slovenia      89
97                            NaN                        Luxembourg      89
77                            NaN                              Iraq      92
171                           NaN              United Arab Emirates      98
101                           NaN                          Malaysia     100
277                        Oregon                                US     101
150                           NaN                      South Africa     103
193              British Columbia                            Canada     109
108                           NaN                           Moldova     111
263                    New Mexico                                US     112
143                           NaN                            Serbia     125
240                        Kansas                                US     134
63                            NaN                            Greece     139
202                      Delaware                                US     144
235                          Iowa                                US     148
141                           NaN                      Saudi Arabia     157
12                            NaN                        Bangladesh     163
112                           NaN                           Morocco     168
125                           NaN                            Panama     178
302                     Tennessee                                US     195
205          District of Columbia                                US     205
56                            NaN                           Finland     206
122                           NaN                            Norway     207
275                      Oklahoma                                US     214
6                             NaN                         Argentina     214
79                            NaN                            Israel     215
33                            NaN                             Chile     216
41                            NaN                    Czech Republic     227
258                        Nevada                                US     230
298                South Carolina                                US     231
241                      Kentucky                                US     234
151                           NaN                       South Korea     247
170                           NaN                           Ukraine     250
253                   Mississippi                                US     250
287                  Rhode Island                                US     251
181                       Alabama                                US     256
34                            NaN                          Colombia     278
46                            NaN                Dominican Republic     293
72                            NaN                           Hungary     300
186                       Arizona                                US     308
315                     Wisconsin                                US     308
252                     Minnesota                                US     319
254                      Missouri                                US     338
124                           NaN                          Pakistan     343
48                            NaN                             Egypt     380
268                North Carolina                                US     382
83                            NaN                             Japan     413
42                            NaN                           Denmark     443
2                             NaN                           Algeria     444
311                      Virginia                                US     522
129                           NaN                       Philippines     558
8                             NaN                           Austria     580
130                           NaN                            Poland     624
133                           NaN                           Romania     693
303                         Texas                                US     754

In [33]:
pd.set_option('display.max_rows', None)

In [34]:
df.sort_values(by="Deaths")

,Date,State,Region,Confirmed,Deaths,Recovered
210,4/29/2020,French Polynesia,France,58,0,50
114,4/29/2020,NaN,Namibia,16,0,8
29,4/29/2020,NaN,Cambodia,122,0,119
113,4/29/2020,NaN,Mozambique,76,0,12
31,4/29/2020,NaN,Central African Republic,50,0,10
110,4/29/2020,NaN,Mongolia,38,0,10
259,4/29/2020,New Brunswick,Canada,118,0,0
260,4/29/2020,New Caledonia,France,18,0,17
99,4/29/2020,NaN,Madagascar,128,0,90
115,4/29/2020,NaN,Nepal,57,0,16
90,4/29/2020,NaN,Laos,19,0,7
271,4/29/2020,Northern Territory,Australia,28,0,25
279,4/29/2020,Prince Edward Island,Canada,27,0,0
281,4/29/2020,Qinghai,Mainland China,18,0,18
286,4/29/2020,Reunion,France,420,0,300
45,4/29/2020,NaN,Dominica,16,0,13
64,4/29/2020,NaN,Grenada,20,0,13
55,4/29/2020,NaN,Fiji,18,0,12
294,4/29/2020,Shanxi,Mainland China,197,0,164
267,4/29/2020,Ningxia,Mainland China,75,0,75
237,4/29/2020,Jiangsu,Mainland China,653,0,648
244,4/29/2020,Macau,Macau,45,0,34
175,4/29/2020,NaN,Vietnam,270,0,222
318,4/29/2020,Yukon,Canada,11,0,0
207,4/29/2020,Faroe Islands,Denmark,187,0,181
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
214,4/29/2020,Gibraltar,UK,141,0,131
215,4/29/2020,Grand Princess,Canada,13,0,0
217,4/29/2020,Greenland,Denmark,11,0,11
135,4/29/2020,NaN,Rwanda,225,0,98
169,4/29/2020,NaN,Uganda,81,0,52
51,4/29/2020,NaN,Eritrea,39,0,19
152,4/29/2020,NaN,South Sudan,34,0,0
136,4/29/2020,NaN,Saint Kitts and Nevis,15,0,4
163,4/29/2020,NaN,Timor-Leste,24,0,6
138,4/29/2020,NaN,Saint Vincent and the Grenadines,16,0,8
137,4/29/2020,NaN,Saint Lucia,17,0,15
144,4/29/2020,NaN,Seychelles,11,0,6
196,4/29/2020,Cayman Islands,UK,73,1,10
95,4/29/2020,NaN,Liechtenstein,82,1,55
201,4/29/2020,Curacao,Netherlands,16,1,13
209,4/29/2020,French Guiana,France,125,1,93
67,4/29/2020,NaN,Guinea-Bissau,205,1,19
256,4/29/2020,Montserrat,UK,11,1,2
53,4/29/2020,NaN,Eswatini,91,1,10
239,4/29/2020,Jilin,Mainland China,111,1,99
211,4/29/2020,Fujian,Mainland China,355,1,353
234,4/29/2020,Inner Mongolia,Mainland China,200,1,150
238,4/29/2020,Jiangxi,Mainland China,937,1,936
320,4/29/2020,Zhejiang,Mainland China,1268,1,1263
102,4/29/2020,NaN,Maldives,278,1,17
27,4/29/2020,NaN,Burundi,11,1,4
17,4/29/2020,NaN,Benin,64,1,33
28,4/29/2020,NaN,Cabo Verde,114,1,2
23,4/29/2020,NaN,Brunei,138,1,124
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
50,4/29/2020,NaN,Equatorial Guinea,315,1,9
21,4/29/2020,NaN,Botswana,23,1,5
94,4/29/2020,NaN,Libya,61,2,18
270,4/29/2020,Northern Mariana Islands,US,14,2,0
221,4/29/2020,Guangxi,Mainland China,254,2,252
32,4/29/2020,NaN,Chad,52,2,19
176,4/29/2020,NaN,West Bank and Gaza,344,2,71
4,4/29/2020,NaN,Angola,27,2,7
222,4/29/2020,Guizhou,Mainland China,147,2,145
212,4/29/2020,Gansu,Mainland China,139,2,137
319,4/29/2020,Yunnan,Mainland China,185,2,181
16,4/29/2020,NaN,Belize,18,2,9
44,4/29/2020,NaN,Djibouti,1077,2,599
242,4/29/2020,Liaoning,Mainland China,146,2,143
188,4/29/2020,Aruba,Netherlands,100,2,73
266,4/29/2020,Newfoundland and Labrador,Canada,258,3,0
100,4/29/2020,NaN,Malawi,36,3,7
54,4/29/2020,NaN,Ethiopia,130,3,58
300,4/29/2020,St Martin,France,38,3,24
304,4/29/2020,Tianjin,Mainland China,190,3,183
295,4/29/2020,Sichuan,Mainland China,561,3,558
179,4/29/2020,NaN,Zambia,97,3,54
216,4/29/2020,Grand Princess,US,103,3,0
5,4/29/2020,NaN,Antigua and Barbuda,24,3,11
291,4/29/2020,Shaanxi,Mainland China,306,3,253
189,4/29/2020,Australian Capital Territory,Australia,106,3,101
118,4/29/2020,NaN,Nicaragua,13,3,7
159,4/29/2020,NaN,Syria,43,3,21
317,4/29/2020,Xinjiang,Mainland China,76,3,73
58,4/29/2020,NaN,Gabon,276,3,67
230,4/29/2020,Hunan,Mainland China,1019,4,1015
228,4/29/2020,Hong Kong,Hong Kong,1037,4,830
109,4/29/2020,NaN,Monaco,95,4,58
104,4/29/2020,NaN,Malta,463,4,339
145,4/29/2020,NaN,Sierra Leone,104,4,12
250,4/29/2020,Mayotte,France,460,4,235
310,4/29/2020,Virgin Islands,US,57,4,0
297,4/29/2020,South Australia,Australia,438,4,420
180,4/29/2020,NaN,Zimbabwe,32,4,5
219,4/29/2020,Guam,US,141,5,0
198,4/29/2020,Chongqing,Mainland China,579,6,573
60,4/29/2020,NaN,Georgia,517,6,178
191,4/29/2020,Bermuda,UK,111,6,48
290,4/29/2020,Saskatchewan,Canada,383,6,0
69,4/29/2020,NaN,Haiti,76,6,8
246,4/29/2020,Manitoba,Canada,275,6,0
283,4/29/2020,Queensland,Australia,1033,6,943
185,4/29/2020,Anhui,Mainland China,991,6,985
160,4/29/2020,NaN,Taiwan,429,6,311
26,4/29/2020,NaN,Burma,150,6,27
37,4/29/2020,NaN,Costa Rica,713,6,323
225,4/29/2020,Hebei,Mainland China,328,6,318
223,4/29/2020,Hainan,Mainland China,168,6,162
293,4/29/2020,Shanghai,Mainland China,647,7,597
292,4/29/2020,Shandong,Mainland China,787,7,772
316,4/29/2020,Wyoming,US,545,7,0
66,4/29/2020,NaN,Guinea,1351,7,313
82,4/29/2020,NaN,Jamaica,396,7,29
154,4/29/2020,NaN,Sri Lanka,649,7,136
111,4/29/2020,NaN,Montenegro,322,7,203
164,4/29/2020,NaN,Togo,109,7,64
13,4/29/2020,NaN,Barbados,80,7,39
165,4/29/2020,NaN,Trinidad and Tobago,116,8,71
220,4/29/2020,Guangdong,Mainland China,1588,8,1557
84,4/29/2020,NaN,Jordan,451,8,356
11,4/29/2020,NaN,Bahrain,2921,8,1455
35,4/29/2020,NaN,Congo (Brazzaville),207,8,19
89,4/29/2020,NaN,Kyrgyzstan,729,8,437
314,4/29/2020,Western Australia,Australia,551,8,507
68,4/29/2020,NaN,Guyana,78,8,18
190,4/29/2020,Beijing,Mainland China,593,9,542
127,4/29/2020,NaN,Paraguay,239,9,102
173,4/29/2020,NaN,Uzbekistan,2002,9,1096
182,4/29/2020,Alaska,US,355,9,0
49,4/29/2020,NaN,El Salvador,377,9,106
142,4/29/2020,NaN,Senegal,882,9,315
174,4/29/2020,NaN,Venezuela,331,10,142
132,4/29/2020,NaN,Qatar,12564,10,1243
73,4/29/2020,NaN,Iceland,1797,10,1656
123,4/29/2020,NaN,Oman,2274,10,364
106,4/29/2020,NaN,Mauritius,332,10,306
10,4/29/2020,NaN,Bahamas,80,11,23
301,4/29/2020,Tasmania,Australia,219,12,144
87,4/29/2020,NaN,Kosovo,510,12,93
218,4/29/2020,Guadeloupe,France,149,12,82
296,4/29/2020,Sint Maarten,Netherlands,75,13,33
43,4/29/2020,NaN,Diamond Princess,712,13,645
299,4/29/2020,South Dakota,US,2373,13,0
226,4/29/2020,Heilongjiang,Mainland China,939,13,587
146,4/29/2020,NaN,Singapore,15641,14,1188
81,4/29/2020,NaN,Ivory Coast,1238,14,557
247,4/29/2020,Martinique,France,175,14,83
86,4/29/2020,NaN,Kenya,384,15,129
40,4/29/2020,NaN,Cyprus,843,15,148
91,4/29/2020,NaN,Latvia,849,15,348
172,4/29/2020,NaN,Uruguay,630,15,412
93,4/29/2020,NaN,Liberia,141,16,45
65,4/29/2020,NaN,Guatemala,557,16,62
62,4/29/2020,NaN,Ghana,1671,16,188
224,4/29/2020,Hawaii,US,613,16,0
255,4/29/2020,Montana,US,451,16,0
161,4/29/2020,NaN,Tanzania,480,16,167
309,4/29/2020,Victoria,Australia,1361,18,1291
269,4/29/2020,North Dakota,US,1033,19,0
117,4/29/2020,NaN,New Zealand,1476,19,1241
236,4/29/2020,Isle of Man,UK,313,21,258
147,4/29/2020,NaN,Slovakia,1391,22,484
227,4/29/2020,Henan,Mainland China,1276,22,1254
9,4/29/2020,NaN,Azerbaijan,1766,23,1267
92,4/29/2020,NaN,Lebanon,721,24,150
88,4/29/2020,NaN,Kuwait,3740,24,1389
103,4/29/2020,NaN,Mali,482,25,129
85,4/29/2020,NaN,Kazakhstan,3138,25,819
273,4/29/2020,Nova Scotia,Canada,935,28,0
149,4/29/2020,NaN,Somalia,582,28,20
155,4/29/2020,NaN,Sudan,375,28,32
1,4/29/2020,NaN,Albania,766,30,455
7,4/29/2020,NaN,Armenia,1932,30,900
36,4/29/2020,NaN,Congo (Kinshasa),491,30,59
119,4/29/2020,NaN,Niger,713,32,435
197,4/29/2020,Channel Islands,UK,537,38,386
313,4/29/2020,West Virginia,US,1110,38,0
264,4/29/2020,New South Wales,Australia,3016,40,2284
166,4/29/2020,NaN,Tunisia,980,40,294
139,4/29/2020,NaN,San Marino,563,41,69
3,4/29/2020,NaN,Andorra,743,42,423
25,4/29/2020,NaN,Burkina Faso,641,43,498
307,4/29/2020,Utah,US,4497,45,0
96,4/29/2020,NaN,Lithuania,1375,45,563
308,4/29/2020,Vermont,US,862,47,0
52,4/29/2020,NaN,Estonia,1666,50,236
120,4/29/2020,NaN,Nigeria,1728,51,307
245,4/29/2020,Maine,US,1056,52,0
162,4/29/2020,NaN,Thailand,2947,54,2665
257,4/29/2020,Nebraska,US,3851,56,0
187,4/29/2020,Arkansas,US,3193,57,0
39,4/29/2020,NaN,Cuba,1467,58,617
19,4/29/2020,NaN,Bolivia,1110,59,117
231,4/29/2020,Idaho,US,1952,60,0
261,4/29/2020,New Hampshire,US,2058,60,0
0,4/29/2020,NaN,Afghanistan,1939,60,252
30,4/29/2020,NaN,Cameroon,1832,61,934
24,4/29/2020,NaN,Bulgaria,1447,64,243
20,4/29/2020,NaN,Bosnia and Herzegovina,1677,65,710
71,4/29/2020,NaN,Honduras,738,66,73
38,4/29/2020,NaN,Croatia,2062,67,1288
121,4/29/2020,NaN,North Macedonia,1442,73,627
14,4/29/2020,NaN,Belarus,13181,84,2072
280,4/29/2020,Puerto Rico,US,1433,86,0
183,4/29/2020,Alberta,Canada,5165,87,0
148,4/29/2020,NaN,Slovenia,1418,89,230
97,4/29/2020,NaN,Luxembourg,3769,89,3134
77,4/29/2020,NaN,Iraq,2003,92,1346
171,4/29/2020,NaN,United Arab Emirates,11929,98,2329
101,4/29/2020,NaN,Malaysia,5945,100,4087
277,4/29/2020,Oregon,US,2446,101,0
150,4/29/2020,NaN,South Africa,5350,103,2073
193,4/29/2020,British Columbia,Canada,2087,109,0
108,4/29/2020,NaN,Moldova,3771,111,1114
263,4/29/2020,New Mexico,US,3213,112,0
143,4/29/2020,NaN,Serbia,6630,125,870
240,4/29/2020,Kansas,US,3839,134,0
63,4/29/2020,NaN,Greece,2576,139,577
202,4/29/2020,Delaware,US,4655,144,0
235,4/29/2020,Iowa,US,6843,148,0
141,4/29/2020,NaN,Saudi Arabia,21402,157,2953
12,4/29/2020,NaN,Bangladesh,7103,163,150
112,4/29/2020,NaN,Morocco,4321,168,928
125,4/29/2020,NaN,Panama,6378,178,527
302,4/29/2020,Tennessee,US,10366,195,0
205,4/29/2020,District of Columbia,US,4106,205,0
56,4/29/2020,NaN,Finland,4906,206,2800
122,4/29/2020,NaN,Norway,7710,207,32
275,4/29/2020,Oklahoma,US,3473,214,0
6,4/29/2020,NaN,Argentina,4285,214,1192
79,4/29/2020,NaN,Israel,15834,215,8233
33,4/29/2020,NaN,Chile,14885,216,8057
41,4/29/2020,NaN,Czech Republic,7579,227,3108
258,4/29/2020,Nevada,US,4934,230,0
298,4/29/2020,South Carolina,US,5882,231,0
241,4/29/2020,Kentucky,US,4537,234,0
151,4/29/2020,NaN,South Korea,10765,247,9059
170,4/29/2020,NaN,Ukraine,9866,250,1103
253,4/29/2020,Mississippi,US,6569,250,0
287,4/29/2020,Rhode Island,US,8247,251,0
181,4/29/2020,Alabama,US,6912,256,0
34,4/29/2020,NaN,Colombia,6207,278,1411
46,4/29/2020,NaN,Dominican Republic,6652,293,1228
72,4/29/2020,NaN,Hungary,2727,300,536
186,4/29/2020,Arizona,US,7209,308,0
315,4/29/2020,Wisconsin,US,6520,308,0
252,4/29/2020,Minnesota,US,4644,319,0
254,4/29/2020,Missouri,US,7660,338,0
124,4/29/2020,NaN,Pakistan,15525,343,3425
48,4/29/2020,NaN,Egypt,5268,380,1335
268,4/29/2020,North Carolina,US,10180,382,0
83,4/29/2020,NaN,Japan,13895,413,2368
42,4/29/2020,NaN,Denmark,9008,443,6366
2,4/29/2020,NaN,Algeria,3848,444,1702
311,4/29/2020,Virginia,US,14962,522,0
129,4/29/2020,NaN,Philippines,8212,558,1023
8,4/29/2020,NaN,Austria,15402,580,12779
130,4/29/2020,NaN,Poland,12640,624,3025
133,4/29/2020,NaN,Romania,11978,693,3569
303,4/29/2020,Texas,US,27257,754,0
199,4/29/2020,Colorado,US,14758,766,0
75,4/29/2020,NaN,Indonesia,9771,784,1391
312,4/29/2020,Washington,US,14070,801,0
47,4/29/2020,NaN,Ecuador,24675,883,1557
274,4/29/2020,Ohio,US,17303,937,0
128,4/29/2020,NaN,Peru,33931,943,10037
233,4/29/2020,Indiana,US,17182,964,0
134,4/29/2020,NaN,Russia,99399,972,10286
131,4/29/2020,NaN,Portugal,24505,973,1470
248,4/29/2020,Maryland,US,20849,1078,0
74,4/29/2020,NaN,India,33062,1079,8437
213,4/29/2020,Georgia,US,25775,1101,0
276,4/29/2020,Ontario,Canada,16978,1153,0
78,4/29/2020,NaN,Ireland,20253,1190,13386
208,4/29/2020,Florida,US,33193,1218,0
158,4/29/2020,NaN,Switzerland,29407,1716,22600
107,4/29/2020,NaN,Mexico,17799,1732,11423
282,4/29/2020,Quebec,Canada,26610,1762,0
243,4/29/2020,Louisiana,US,27660,1845,0
195,4/29/2020,California,US,48747,1946,0
200,4/29/2020,Connecticut,US,26767,2169,0
232,4/29/2020,Illinois,US,50358,2215,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
157,4/29/2020,NaN,Sweden,20302,2462,1005
167,4/29/2020,NaN,Turkey,117589,3081,44040
249,4/29/2020,Massachusetts,US,60265,3405,0
251,4/29/2020,Michigan,US,40399,3670,0
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
116,4/29/2020,NaN,Netherlands,38802,4711,0
22,4/29/2020,NaN,Brazil,79685,5513,34132
76,4/29/2020,NaN,Iran,93657,5957,73791
61,4/29/2020,NaN,Germany,161539,6467,120400
262,4/29/2020,New Jersey,US,116365,6771,0
15,4/29/2020,NaN,Belgium,47859,7501,11283
265,4/29/2020,New York,US,299691,23477,0
57,4/29/2020,NaN,France,165093,24087,48228
153,4/29/2020,NaN,Spain,236899,24275,132929
168,4/29/2020,NaN,UK,165221,26097,0
80,4/29/2020,NaN,Italy,203591,27682,71252

In [36]:
df.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [38]:
answer="France"

Q. 5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?

In [39]:
df["Region"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Central African Republic', 'Chad',
       'Chile', 'Colombia', 'Congo (Brazzaville)', 'Congo (Kinshasa)',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
       'Denmark', 'Diamond Princess', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Fiji', 'Finland', 'France', 'Gabon', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Mauritius', 'Mexico', 'Moldova',
       'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'UK', 'Uganda', 'Ukraine', 'United Arab Emirates', 'Uruguay',
       'Uzbekistan', 'Venezuela', 'Vietnam', 'West Bank and Gaza',
       'Zambia', 'Zimbabwe', 'US', 'Canada', 'Mainland China',
       'Australia', 'Hong Kong', 'Macau'], dtype=object)

In [40]:
df[df["Region"]=="India"]

         Date State Region  Confirmed  Deaths  Recovered
74  4/29/2020   NaN  India      33062    1079       8437

In [41]:
df

,Date,State,Region,Confirmed,Deaths,Recovered
0,4/29/2020,NaN,Afghanistan,1939,60,252
1,4/29/2020,NaN,Albania,766,30,455
2,4/29/2020,NaN,Algeria,3848,444,1702
3,4/29/2020,NaN,Andorra,743,42,423
4,4/29/2020,NaN,Angola,27,2,7
5,4/29/2020,NaN,Antigua and Barbuda,24,3,11
6,4/29/2020,NaN,Argentina,4285,214,1192
7,4/29/2020,NaN,Armenia,1932,30,900
8,4/29/2020,NaN,Austria,15402,580,12779
9,4/29/2020,NaN,Azerbaijan,1766,23,1267
10,4/29/2020,NaN,Bahamas,80,11,23
11,4/29/2020,NaN,Bahrain,2921,8,1455
12,4/29/2020,NaN,Bangladesh,7103,163,150
13,4/29/2020,NaN,Barbados,80,7,39
14,4/29/2020,NaN,Belarus,13181,84,2072
15,4/29/2020,NaN,Belgium,47859,7501,11283
16,4/29/2020,NaN,Belize,18,2,9
17,4/29/2020,NaN,Benin,64,1,33
19,4/29/2020,NaN,Bolivia,1110,59,117
20,4/29/2020,NaN,Bosnia and Herzegovina,1677,65,710
21,4/29/2020,NaN,Botswana,23,1,5
22,4/29/2020,NaN,Brazil,79685,5513,34132
23,4/29/2020,NaN,Brunei,138,1,124
24,4/29/2020,NaN,Bulgaria,1447,64,243
25,4/29/2020,NaN,Burkina Faso,641,43,498
26,4/29/2020,NaN,Burma,150,6,27
27,4/29/2020,NaN,Burundi,11,1,4
28,4/29/2020,NaN,Cabo Verde,114,1,2
29,4/29/2020,NaN,Cambodia,122,0,119
30,4/29/2020,NaN,Cameroon,1832,61,934
31,4/29/2020,NaN,Central African Republic,50,0,10
32,4/29/2020,NaN,Chad,52,2,19
33,4/29/2020,NaN,Chile,14885,216,8057
34,4/29/2020,NaN,Colombia,6207,278,1411
35,4/29/2020,NaN,Congo (Brazzaville),207,8,19
36,4/29/2020,NaN,Congo (Kinshasa),491,30,59
37,4/29/2020,NaN,Costa Rica,713,6,323
38,4/29/2020,NaN,Croatia,2062,67,1288
39,4/29/2020,NaN,Cuba,1467,58,617
40,4/29/2020,NaN,Cyprus,843,15,148
41,4/29/2020,NaN,Czech Republic,7579,227,3108
42,4/29/2020,NaN,Denmark,9008,443,6366
43,4/29/2020,NaN,Diamond Princess,712,13,645
44,4/29/2020,NaN,Djibouti,1077,2,599
45,4/29/2020,NaN,Dominica,16,0,13
46,4/29/2020,NaN,Dominican Republic,6652,293,1228
47,4/29/2020,NaN,Ecuador,24675,883,1557
48,4/29/2020,NaN,Egypt,5268,380,1335
49,4/29/2020,NaN,El Salvador,377,9,106
50,4/29/2020,NaN,Equatorial Guinea,315,1,9
51,4/29/2020,NaN,Eritrea,39,0,19
52,4/29/2020,NaN,Estonia,1666,50,236
53,4/29/2020,NaN,Eswatini,91,1,10
54,4/29/2020,NaN,Ethiopia,130,3,58
55,4/29/2020,NaN,Fiji,18,0,12
56,4/29/2020,NaN,Finland,4906,206,2800
57,4/29/2020,NaN,France,165093,24087,48228
58,4/29/2020,NaN,Gabon,276,3,67
60,4/29/2020,NaN,Georgia,517,6,178
61,4/29/2020,NaN,Germany,161539,6467,120400
62,4/29/2020,NaN,Ghana,1671,16,188
63,4/29/2020,NaN,Greece,2576,139,577
64,4/29/2020,NaN,Grenada,20,0,13
65,4/29/2020,NaN,Guatemala,557,16,62
66,4/29/2020,NaN,Guinea,1351,7,313
67,4/29/2020,NaN,Guinea-Bissau,205,1,19
68,4/29/2020,NaN,Guyana,78,8,18
69,4/29/2020,NaN,Haiti,76,6,8
71,4/29/2020,NaN,Honduras,738,66,73
72,4/29/2020,NaN,Hungary,2727,300,536
73,4/29/2020,NaN,Iceland,1797,10,1656
74,4/29/2020,NaN,India,33062,1079,8437
75,4/29/2020,NaN,Indonesia,9771,784,1391
76,4/29/2020,NaN,Iran,93657,5957,73791
77,4/29/2020,NaN,Iraq,2003,92,1346
78,4/29/2020,NaN,Ireland,20253,1190,13386
79,4/29/2020,NaN,Israel,15834,215,8233
80,4/29/2020,NaN,Italy,203591,27682,71252
81,4/29/2020,NaN,Ivory Coast,1238,14,557
82,4/29/2020,NaN,Jamaica,396,7,29
83,4/29/2020,NaN,Japan,13895,413,2368
84,4/29/2020,NaN,Jordan,451,8,356
85,4/29/2020,NaN,Kazakhstan,3138,25,819
86,4/29/2020,NaN,Kenya,384,15,129
87,4/29/2020,NaN,Kosovo,510,12,93
88,4/29/2020,NaN,Kuwait,3740,24,1389
89,4/29/2020,NaN,Kyrgyzstan,729,8,437
90,4/29/2020,NaN,Laos,19,0,7
91,4/29/2020,NaN,Latvia,849,15,348
92,4/29/2020,NaN,Lebanon,721,24,150
93,4/29/2020,NaN,Liberia,141,16,45
94,4/29/2020,NaN,Libya,61,2,18
95,4/29/2020,NaN,Liechtenstein,82,1,55
96,4/29/2020,NaN,Lithuania,1375,45,563
97,4/29/2020,NaN,Luxembourg,3769,89,3134
99,4/29/2020,NaN,Madagascar,128,0,90
100,4/29/2020,NaN,Malawi,36,3,7
101,4/29/2020,NaN,Malaysia,5945,100,4087
102,4/29/2020,NaN,Maldives,278,1,17
103,4/29/2020,NaN,Mali,482,25,129
104,4/29/2020,NaN,Malta,463,4,339
106,4/29/2020,NaN,Mauritius,332,10,306
107,4/29/2020,NaN,Mexico,17799,1732,11423
108,4/29/2020,NaN,Moldova,3771,111,1114
109,4/29/2020,NaN,Monaco,95,4,58
110,4/29/2020,NaN,Mongolia,38,0,10
111,4/29/2020,NaN,Montenegro,322,7,203
112,4/29/2020,NaN,Morocco,4321,168,928
113,4/29/2020,NaN,Mozambique,76,0,12
114,4/29/2020,NaN,Namibia,16,0,8
115,4/29/2020,NaN,Nepal,57,0,16
116,4/29/2020,NaN,Netherlands,38802,4711,0
117,4/29/2020,NaN,New Zealand,1476,19,1241
118,4/29/2020,NaN,Nicaragua,13,3,7
119,4/29/2020,NaN,Niger,713,32,435
120,4/29/2020,NaN,Nigeria,1728,51,307
121,4/29/2020,NaN,North Macedonia,1442,73,627
122,4/29/2020,NaN,Norway,7710,207,32
123,4/29/2020,NaN,Oman,2274,10,364
124,4/29/2020,NaN,Pakistan,15525,343,3425
125,4/29/2020,NaN,Panama,6378,178,527
127,4/29/2020,NaN,Paraguay,239,9,102
128,4/29/2020,NaN,Peru,33931,943,10037
129,4/29/2020,NaN,Philippines,8212,558,1023
130,4/29/2020,NaN,Poland,12640,624,3025
131,4/29/2020,NaN,Portugal,24505,973,1470
132,4/29/2020,NaN,Qatar,12564,10,1243
133,4/29/2020,NaN,Romania,11978,693,3569
134,4/29/2020,NaN,Russia,99399,972,10286
135,4/29/2020,NaN,Rwanda,225,0,98
136,4/29/2020,NaN,Saint Kitts and Nevis,15,0,4
137,4/29/2020,NaN,Saint Lucia,17,0,15
138,4/29/2020,NaN,Saint Vincent and the Grenadines,16,0,8
139,4/29/2020,NaN,San Marino,563,41,69
141,4/29/2020,NaN,Saudi Arabia,21402,157,2953
142,4/29/2020,NaN,Senegal,882,9,315
143,4/29/2020,NaN,Serbia,6630,125,870
144,4/29/2020,NaN,Seychelles,11,0,6
145,4/29/2020,NaN,Sierra Leone,104,4,12
146,4/29/2020,NaN,Singapore,15641,14,1188
147,4/29/2020,NaN,Slovakia,1391,22,484
148,4/29/2020,NaN,Slovenia,1418,89,230
149,4/29/2020,NaN,Somalia,582,28,20
150,4/29/2020,NaN,South Africa,5350,103,2073
151,4/29/2020,NaN,South Korea,10765,247,9059
152,4/29/2020,NaN,South Sudan,34,0,0
153,4/29/2020,NaN,Spain,236899,24275,132929
154,4/29/2020,NaN,Sri Lanka,649,7,136
155,4/29/2020,NaN,Sudan,375,28,32
157,4/29/2020,NaN,Sweden,20302,2462,1005
158,4/29/2020,NaN,Switzerland,29407,1716,22600
159,4/29/2020,NaN,Syria,43,3,21
160,4/29/2020,NaN,Taiwan,429,6,311
161,4/29/2020,NaN,Tanzania,480,16,167
162,4/29/2020,NaN,Thailand,2947,54,2665
163,4/29/2020,NaN,Timor-Leste,24,0,6
164,4/29/2020,NaN,Togo,109,7,64
165,4/29/2020,NaN,Trinidad and Tobago,116,8,71
166,4/29/2020,NaN,Tunisia,980,40,294
167,4/29/2020,NaN,Turkey,117589,3081,44040
168,4/29/2020,NaN,UK,165221,26097,0
169,4/29/2020,NaN,Uganda,81,0,52
170,4/29/2020,NaN,Ukraine,9866,250,1103
171,4/29/2020,NaN,United Arab Emirates,11929,98,2329
172,4/29/2020,NaN,Uruguay,630,15,412
173,4/29/2020,NaN,Uzbekistan,2002,9,1096
174,4/29/2020,NaN,Venezuela,331,10,142
175,4/29/2020,NaN,Vietnam,270,0,222
176,4/29/2020,NaN,West Bank and Gaza,344,2,71
179,4/29/2020,NaN,Zambia,97,3,54
180,4/29/2020,NaN,Zimbabwe,32,4,5
181,4/29/2020,Alabama,US,6912,256,0
182,4/29/2020,Alaska,US,355,9,0
183,4/29/2020,Alberta,Canada,5165,87,0
185,4/29/2020,Anhui,Mainland China,991,6,985
186,4/29/2020,Arizona,US,7209,308,0
187,4/29/2020,Arkansas,US,3193,57,0
188,4/29/2020,Aruba,Netherlands,100,2,73
189,4/29/2020,Australian Capital Territory,Australia,106,3,101
190,4/29/2020,Beijing,Mainland China,593,9,542
191,4/29/2020,Bermuda,UK,111,6,48
193,4/29/2020,British Columbia,Canada,2087,109,0
195,4/29/2020,California,US,48747,1946,0
196,4/29/2020,Cayman Islands,UK,73,1,10
197,4/29/2020,Channel Islands,UK,537,38,386
198,4/29/2020,Chongqing,Mainland China,579,6,573
199,4/29/2020,Colorado,US,14758,766,0
200,4/29/2020,Connecticut,US,26767,2169,0
201,4/29/2020,Curacao,Netherlands,16,1,13
202,4/29/2020,Delaware,US,4655,144,0
204,4/29/2020,Diamond Princess cruise ship,US,49,0,0
205,4/29/2020,District of Columbia,US,4106,205,0
206,4/29/2020,Falkland Islands (Malvinas),UK,13,0,11
207,4/29/2020,Faroe Islands,Denmark,187,0,181
208,4/29/2020,Florida,US,33193,1218,0
209,4/29/2020,French Guiana,France,125,1,93
210,4/29/2020,French Polynesia,France,58,0,50
211,4/29/2020,Fujian,Mainland China,355,1,353
212,4/29/2020,Gansu,Mainland China,139,2,137
213,4/29/2020,Georgia,US,25775,1101,0
214,4/29/2020,Gibraltar,UK,141,0,131
215,4/29/2020,Grand Princess,Canada,13,0,0
216,4/29/2020,Grand Princess,US,103,3,0
217,4/29/2020,Greenland,Denmark,11,0,11
218,4/29/2020,Guadeloupe,France,149,12,82
219,4/29/2020,Guam,US,141,5,0
220,4/29/2020,Guangdong,Mainland China,1588,8,1557
221,4/29/2020,Guangxi,Mainland China,254,2,252
222,4/29/2020,Guizhou,Mainland China,147,2,145
223,4/29/2020,Hainan,Mainland China,168,6,162
224,4/29/2020,Hawaii,US,613,16,0
225,4/29/2020,Hebei,Mainland China,328,6,318
226,4/29/2020,Heilongjiang,Mainland China,939,13,587
227,4/29/2020,Henan,Mainland China,1276,22,1254
228,4/29/2020,Hong Kong,Hong Kong,1037,4,830
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
230,4/29/2020,Hunan,Mainland China,1019,4,1015
231,4/29/2020,Idaho,US,1952,60,0
232,4/29/2020,Illinois,US,50358,2215,0
233,4/29/2020,Indiana,US,17182,964,0
234,4/29/2020,Inner Mongolia,Mainland China,200,1,150
235,4/29/2020,Iowa,US,6843,148,0
236,4/29/2020,Isle of Man,UK,313,21,258
237,4/29/2020,Jiangsu,Mainland China,653,0,648
238,4/29/2020,Jiangxi,Mainland China,937,1,936
239,4/29/2020,Jilin,Mainland China,111,1,99
240,4/29/2020,Kansas,US,3839,134,0
241,4/29/2020,Kentucky,US,4537,234,0
242,4/29/2020,Liaoning,Mainland China,146,2,143
243,4/29/2020,Louisiana,US,27660,1845,0
244,4/29/2020,Macau,Macau,45,0,34
245,4/29/2020,Maine,US,1056,52,0
246,4/29/2020,Manitoba,Canada,275,6,0
247,4/29/2020,Martinique,France,175,14,83
248,4/29/2020,Maryland,US,20849,1078,0
249,4/29/2020,Massachusetts,US,60265,3405,0
250,4/29/2020,Mayotte,France,460,4,235
251,4/29/2020,Michigan,US,40399,3670,0
252,4/29/2020,Minnesota,US,4644,319,0
253,4/29/2020,Mississippi,US,6569,250,0
254,4/29/2020,Missouri,US,7660,338,0
255,4/29/2020,Montana,US,451,16,0
256,4/29/2020,Montserrat,UK,11,1,2
257,4/29/2020,Nebraska,US,3851,56,0
258,4/29/2020,Nevada,US,4934,230,0
259,4/29/2020,New Brunswick,Canada,118,0,0
260,4/29/2020,New Caledonia,France,18,0,17
261,4/29/2020,New Hampshire,US,2058,60,0
262,4/29/2020,New Jersey,US,116365,6771,0
263,4/29/2020,New Mexico,US,3213,112,0
264,4/29/2020,New South Wales,Australia,3016,40,2284
265,4/29/2020,New York,US,299691,23477,0
266,4/29/2020,Newfoundland and Labrador,Canada,258,3,0
267,4/29/2020,Ningxia,Mainland China,75,0,75
268,4/29/2020,North Carolina,US,10180,382,0
269,4/29/2020,North Dakota,US,1033,19,0
270,4/29/2020,Northern Mariana Islands,US,14,2,0
271,4/29/2020,Northern Territory,Australia,28,0,25
273,4/29/2020,Nova Scotia,Canada,935,28,0
274,4/29/2020,Ohio,US,17303,937,0
275,4/29/2020,Oklahoma,US,3473,214,0
276,4/29/2020,Ontario,Canada,16978,1153,0
277,4/29/2020,Oregon,US,2446,101,0
278,4/29/2020,Pennsylvania,US,46327,2373,0
279,4/29/2020,Prince Edward Island,Canada,27,0,0
280,4/29/2020,Puerto Rico,US,1433,86,0
281,4/29/2020,Qinghai,Mainland China,18,0,18
282,4/29/2020,Quebec,Canada,26610,1762,0
283,4/29/2020,Queensland,Australia,1033,6,943
286,4/29/2020,Reunion,France,420,0,300
287,4/29/2020,Rhode Island,US,8247,251,0
290,4/29/2020,Saskatchewan,Canada,383,6,0
291,4/29/2020,Shaanxi,Mainland China,306,3,253
292,4/29/2020,Shandong,Mainland China,787,7,772
293,4/29/2020,Shanghai,Mainland China,647,7,597
294,4/29/2020,Shanxi,Mainland China,197,0,164
295,4/29/2020,Sichuan,Mainland China,561,3,558
296,4/29/2020,Sint Maarten,Netherlands,75,13,33
297,4/29/2020,South Australia,Australia,438,4,420
298,4/29/2020,South Carolina,US,5882,231,0
299,4/29/2020,South Dakota,US,2373,13,0
300,4/29/2020,St Martin,France,38,3,24
301,4/29/2020,Tasmania,Australia,219,12,144
302,4/29/2020,Tennessee,US,10366,195,0
303,4/29/2020,Texas,US,27257,754,0
304,4/29/2020,Tianjin,Mainland China,190,3,183
306,4/29/2020,Turks and Caicos Islands,UK,12,1,5
307,4/29/2020,Utah,US,4497,45,0
308,4/29/2020,Vermont,US,862,47,0
309,4/29/2020,Victoria,Australia,1361,18,1291
310,4/29/2020,Virgin Islands,US,57,4,0
311,4/29/2020,Virginia,US,14962,522,0
312,4/29/2020,Washington,US,14070,801,0
313,4/29/2020,West Virginia,US,1110,38,0
314,4/29/2020,Western Australia,Australia,551,8,507
315,4/29/2020,Wisconsin,US,6520,308,0
316,4/29/2020,Wyoming,US,545,7,0
317,4/29/2020,Xinjiang,Mainland China,76,3,73
318,4/29/2020,Yukon,Canada,11,0,0
319,4/29/2020,Yunnan,Mainland China,185,2,181
320,4/29/2020,Zhejiang,Mainland China,1268,1,1263